workflows:
  ios-pwa-simulator:
    name: PWA iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build # Ensure this creates your 'dist' or 'www' folder
      - name: Initialize Native iOS Project
        script: |
          # This creates the ios folder on the build machine
          npx cap add ios
          npx cap sync ios
      - name: CocoaPods installation
        script: |
          cd ios/App && pod install
      - name: Build for Simulator (No Signing)
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
