workflows:
  ios-pwa-simulator:
    name: PWA iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace"
        XCODE_SCHEME: "CodemagicSample"
    scripts:
      - name: Install dependencies
        script: pod install
      - name: Build for Simulator (No Signing)
        script: |
          # The key flags below (ALLOWED=NO) bypass the need for an Apple Account
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
    artifacts:
      # This produces a .app file which you can run on a Mac Simulator
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
