scripts:
      - name: Install dependencies and Build Web
        script: |
          npm install
          npm run build
      - name: Initialize Native iOS Project
        script: |
          # Clean up any existing ios folder to prevent conflicts
          rm -rf ios
          npx cap add ios
          npx cap sync ios
      - name: CocoaPods installation
        script: |
          # The Podfile is located in ios/App/
          cd ios/App && pod install
      - name: Build for Simulator (No Signing)
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Package for Appetize
        script: |
          # Zip the generated .app for cloud testing
          APP_PATH=$(find build/Build/Products/Debug-iphonesimulator -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then echo "App not found"; exit 1; fi
          cd $(dirname "$APP_PATH")
          zip -r simulator-build.zip $(basename "$APP_PATH")
          mv simulator-build.zip $CM_BUILD_DIR/
    artifacts:
      - simulator-build.zip
