- name: Build for Simulator (No Signing)
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build_output \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
      - name: Package for Appetize
        script: |
          # This finds the actual app folder and zips it up
          APP_PATH=$(find build_output/Build/Products/Debug-iphonesimulator -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then echo "App folder not found"; exit 1; fi
          cd $(dirname "$APP_PATH")
          zip -r simulator-build.zip $(basename "$APP_PATH")
          mv simulator-build.zip $CM_BUILD_DIR/
    artifacts:
      - simulator-build.zip
